### PR TITLE
fix(jenkins_plugin): fix first section expand/collapse on pipeline job

### LINKED ISSUE #352: First log section is always expanded in Jenkins log, if pipeline job is used
## Description

If Universum is executed using Jenkins pipeline job, first log section is always expanded and doesn't collapse on click.

## Steps to reproduce

1. Run Universum inside "sh" block in pipeline job
2. Open console output
3. Try to expand/collapse first section ("Preparing repository")

## Expected result

Section is initially collapsed and expanded on click.

## Actual result

Section is initially expanded and doesn't collapse on click.

## Environment

Jenkins plugin v1.2

### PR DESCRIPTION
**Pull request by miltolstoy**
Resolves #352

### CODE REVIEW

File: universum_log_collapser/src/main/resources/io/jenkins/plugins/universum_log_collapser/Note/script.js [hunk 1]
```diff
@@ -30,6 +32,34 @@ function finishColoring() {
...
+        }
+
+        el.nextSibling.insertAdjacentHTML("beforebegin", el.innerHTML);
+        el.innerHTML = "";
+        fixed = true;
+        break;
+    }
+
+    if (!fixed) {
+        setTimeout(fix_pipeline, 50);
```
Comment (i-keliukh) [inline universum_log_collapser/src/main/resources/io/jenkins/plugins/universum_log_collapser/Note/script.js]: 1. Why you need setTimeout?
2. What is the guarantee it is ever going to finish?

Comment (miltolstoy) [reply universum_log_collapser/src/main/resources/io/jenkins/plugins/universum_log_collapser/Note/script.js]: Refactored in next commit.
